### ISSUE TITLE
Wrong len returned by guess_response_frame_len for Rtu

### ISSUE THREAD

**Issue by franklx** [alttch/rmodbus#1] opened 2020-11-26 07:54 UTC
Function ```guess_response_frame_len``` return 2 extra bytes of lenght.
The problem is at ```lib.rs```@618:
```rust
          ModbusProto::Rtu => (buf, 2),
```
second argument shoud be ```0``` .

**Comment by divi255** [comment] 2020-11-26 14:10
Good day,

the extra is fine, rtu frames have 2 bytes crc. I see the problem is in frame length calc itself, I probably broke it when implemented modbus ascii.

I'll add tests for both later today. Thanks for reporting

**Comment by divi255** [comment] 2020-11-26 19:18
fixed in 0.5.2, tested, seems to work fine

**Closed by divi255** 2020-11-26 19:18 UTC
